### ISSUE TITLE
DB migration시 path 수정

### ISSUE THREAD

**Issue by jupiny** [kei01138/djangoProject#2]
https://github.com/kei01138/djangoProject#django-%ED%99%98%EA%B2%BD%EC%84%B8%ED%8C%85

![image](https://user-images.githubusercontent.com/13096688/52891835-ee26f580-31d0-11e9-8237-1812a9b1ebba.png)
가이드대로 했을시 path가 달라 문제가 생기네요 ㅎㅎ 아래와 같이 수정부탁드립니다.

As-is:
```bash
(myvenv) root@goorm:/workspace/django/mysite# python manage.py migrate
```

To-be:
```bash
(myvenv) root@goorm:/workspace/django/mysite# python tutorialdjango/manage.py migrate
```

or

```bash
(myvenv) root@goorm:/workspace/django/mysite# cd tutorialdjango
(myvenv) root@goorm:/workspace/django/mysite/tutorialdjango# python manage.py migrate
```

**Comment by ChoiKangM** [comment]
`django`가 사용할 DB를 생성합니다(migrate 합니다)
```console
(myvenv) root@goorm:/workspace/django/mysite# cd tutorialdjango
(myvenv) root@goorm:/workspace/django/mysite/tutorialdjango# python manage.py migrate
```

감사합니다 수정 완료했습니다

**Comment by ChoiKangM** [comment]
이제 `django` 프로젝트를 실행합니다  
로컬에서 실행하는 경우 [http://0:80/](http://0:80/)로 접속합니다  
구름 IDE를 사용하는 경우 `/프로젝트/실행 URL과 포트`에서 80번 포트를 설정 후 접속합니다
```console
(myvenv) root@goorm:/workspace/django/mysite/tutorialdjango# python manage.py runserver 0:80 
```
추가적인 수정 완료했습니다

**Comment by jupiny** [comment]
감사합니다. 😃
